### ISSUE TITLE
Outdated for new data structure?

### ISSUE THREAD

**Issue by seunggookim** [neurosynth/neurosynth#101]
Hi everyone!

I was trying to experience Neurosynth at first hand, but I'm afraid that the current version might not work with the updated filename conventions? There is no `https://github.com/neurosynth/neurosynth-data/blob/master/current_data.tar.gz` file anymore yet, in the `dataset` module tries to download it (neurosynth/neurosynth/base/dataset.py: line 38).

I've manually downloaded data files from `https://github.com/neurosynth/neurosynth-data` but there is no file ending in `dataset.txt`. I could only imagine this might have been replaced with `*coordinates.tsv.gz` but then I believe the documentation (and the download module) should be updated.

If I'm missing something, please help this poor noobie! 😢

**Comment by adelavega** [comment]
Hello,

As noted in the README:

```
Note: this package is no longer actively maintained; most of its functionality has been integrated into the much more expansive NiMARE package, which we recommend using instead.
```

I would highly recommend trying out NiMARE for meta-analysis instead

**Comment by seunggookim** [comment]
Oh I missed that. Thank you!
