### ISSUE TITLE
"Default mode network" topic returns error

### ISSUE THREAD

**Issue by chrisfilo** [neurosynth/neurosynth#52]
http://neurosynth.org/analyses/4463/

**Comment by tyarkoni** [comment]
Where is that analysis linked from? The topic maps at /analyses/topics/ all seem to work fine, so I assume the link is coming from some other page...

**Comment by chrisfilo** [comment]
In the "terms" tab: http://neurosynth.org/studies/24821182/

**Comment by vsoch** [comment]
More than one of those links produce the same error

**Comment by vsoch** [comment]
It looks like all with a loading of "1" trigger the error.

**Comment by tyarkoni** [comment]
Ah, thanks. Those are actually not supposed to be linked at all; they're named custom analyses. Will fix ASAP.

In future, please post web-related issues to the neurosynth-web repo.

**Comment by tyarkoni** [comment]
Fixed in https://github.com/neurosynth/neurosynth-web/commit/bcb159f875ef5d689fbfb88a07bb4bc978c439fe
