### ISSUE TITLE
Change the name to something more snappy

### ISSUE THREAD

**Issue by chrisfilo** [neurosynth/neurosynth#56]

**Comment by tyarkoni** [comment]
Uhhh... no.

**Comment by cMadan** [comment]
Do you mean the name of "neurosynth" itself??

**Comment by poldrack** [comment]
so this is what a hackathon is good for?

> On Oct 23, 2015, at 2:34 PM, Chris Filo Gorgolewski <notifications@github.com> wrote:
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/neurosynth/neurosynth/issues/56>.
> 

—
Russell A. Poldrack
Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by chrisfilo** [comment]
What do you think @margulies?

**Comment by tyarkoni** [comment]
Closing this issue and recommending that @chrisfilo seek professional help. And @poldrack : yes :)

**Comment by vsoch** [comment]
This is probably one of my favorite issues of all time... all in under 5 minutes!

**Comment by tyarkoni** [comment]
Well are you just gonna compliment us, @vsoch, or are you actually going to suggest something snappy?

**Comment by margulies** [comment]
Neuromoog?

**Comment by tyarkoni** [comment]
Reopening this issue so we can consider changing the name of my life's work to something snappier.

**Comment by vsoch** [comment]
![this](https://cloud.githubusercontent.com/assets/814322/10705896/88157cf8-7996-11e5-8d7c-4e84d2849542.png)

**Comment by tyarkoni** [comment]
I like it. Closing issue but will rebrand whole project (and life) in coming weeks.

**Comment by yarikoptic** [comment]
Now I am jealous I will not witness in my own eyes this event of the century.

On October 23, 2015 6:11:17 PM EDT, Tal Yarkoni <notifications@github.com> wrote:
>Closed #56.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/neurosynth/neurosynth/issues/56#event-444304329

-- 
Sent from a phone which beats iPhone.

**Comment by zorro4** [comment]
You guys are really silly. FYI
