### ISSUE TITLE
DOI for releases

### ISSUE THREAD

**Issue by vsoch** [neurosynth/neurosynth#59]
How about associating a DOI with a release: https://github.com/neurosynth/neurosynth/releases/tag/0.3.3, for example with https://zenodo.org/record/32508 so I can cite NeuroSynth not once, but multiple times, for the different releases? :)

**Comment by poldrack** [comment]
BTW - we have an account with ezid so we can coin DOIs as needed
cheers
rp
> On Nov 2, 2015, at 12:30 PM, Assenav Sochat <notifications@github.com> wrote:
> 
> How about associating a DOI with a release: https://github.com/neurosynth/neurosynth/releases/tag/0.3.3 <https://github.com/neurosynth/neurosynth/releases/tag/0.3.3>, for example with https://zenodo.org/record/32508 <https://zenodo.org/record/32508> so I can cite NeuroSynth not once, but multiple times, for the different releases? :)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/neurosynth/neurosynth/issues/59>.
> 

—
Russell A. Poldrack
Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by vsoch** [comment]
We do? Wicked! I will use for all future stuffs!

**Comment by poldrack** [comment]
perhaps we should add automatic generation of DOIs to neurosynth?

http://ezid.cdlib.org/doc/apidoc.html <http://ezid.cdlib.org/doc/apidoc.html>

note that once a DOI has been generated it can’t be deleted, so be careful - I think they have a dummy API you can use for testing.
cheers
rp
> On Nov 2, 2015, at 1:08 PM, Assenav Sochat <notifications@github.com> wrote:
> 
> We do? Wicked! I will use for all future stuffs!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/neurosynth/neurosynth/issues/59#issuecomment-153157123>.
> 

—
Russell A. Poldrack
Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by tyarkoni** [comment]
We could definitely attach DOIs to individual data releases, and it's probably worth doing. But I think the broader utility is pretty limited (since the DB only updates once every 6 months or so). Minting DOIs for new meta-analyses, on the other hand, would be *really* useful (i.e., it would allow people to cite individual universally locatable meta-analyses in their papers). I don't think we'd want to allow users to generate DOIs for locally-generated maps, but for "official" releases on the website, that would be great. The main issue is that it would require me to start versioning maps properly, which would add quite a bit of complexity to the neurosynth.org database model. It would obviously be a good thing to do irrespective of issuing DOIs, but is also quite a bit of work. Will think on it...

**Comment by vsoch** [comment]
I think what I was asking about is much simpler, and there are two things that have been brought up here:

1. DOI for data / releases. It would be challenging to version specific releases of the neurosynth-data, especially given that there are new publications all the time. I did not have this in mind, I was thinking of the few versions of the software itself (eg, moving from parsing full papers to abstracts). I'm talking about that in my thesis, and it would be nice to have a DOI associated with the tag in zenodo, which is pretty simple to do. Otherwise, I'll just link to the tag itself.

2. DOI for people's meta-analysis: We could already sort of cite individual meta-analysis with a unique URL in NeuroVault (granted that they share those maps!). As for NeuroSynth meta-analysis, that's your bag of worms Tal! :)

I will cite the tag for now... as you are thinking... :)

**Comment by tyarkoni** [comment]
Oh, I see. I was thinking more about the data releases. I'm ambivalent about giving each package release a new DOI; I think the number of people who have actually used the Python package in a paper and want to cite it is probably in the single digits (or certainly low double digits)---as opposed to the much larger number of people who've used data or maps. But if you have some mock code I can easily adapt, I'm happy to add this.

**Comment by vsoch** [comment]
If you go to zenodo:

https://zenodo.org/

You literally just "turn on" a repo (akin to how you do it with circle, travis, or any other github-integrated thing) and then you can select a tagged release to ascribe a DOI, and click an "are you sure" button and it's done!

Then you get a snazzy badge for your repo, if desired :) I have pretty much accomplished nothing in research, BUT I have such a snazzy badge!

https://github.com/vsoch/image-comparison-thresholding

boum!

**Comment by tyarkoni** [comment]
Oh, yeah... Neurosynth already has a Zenodo DOI:

https://zenodo.org/record/9925?ln=en#.VjgDCa4RFE4

I just don't think it's going to make any practical difference if each release has its own DOI. So far the existing DOI has been cited a grand total of one time. I think I'd rather have people cite the 2011 paper and/or the website.

**Comment by vsoch** [comment]
okey doke, that I can do.
