### ISSUE TITLE
Missing dependency: ply

### ISSUE THREAD

**Issue by vsoch** [neurosynth/neurosynth#60]
I installed neurosynth with pip:

      pip install neurosynth --user

and I am missing a module called ply:

![image](https://cloud.githubusercontent.com/assets/814322/11018068/e8cfb9b0-856b-11e5-89a0-35ca9f9dbed5.png)

**Comment by vsoch** [comment]
Hmm it happened for sklearn too.. does neurosynth not install any dependencies?

**Comment by tyarkoni** [comment]
PyPI Neurosynth is out of date. Install from github for now. Will update.

**Comment by vsoch** [comment]
Will do! For the time being I've added the missing dependencies to my apps setup, so let me know when you get around to updating pypi.

**Comment by tyarkoni** [comment]
Should work now.
