### ISSUE TITLE
scipy.stats.ss deprecated

### ISSUE THREAD

**Issue by cvklein** [neurosynth/neurosynth#76]
scipy.stats.ss has been fully depreciated, which makes analysis/stats.py unhappy. 

(It should be a trivial fix to just drop in the old ss code? But you don't want me mucking around)

**Comment by darksipu** [comment]
We managed to run it by replacing `ss(x)` with `np.sum(x**2)` 

Hopefully the functions was returning the sum of squares? Maybe the authors can confirm

**Comment by adelavega** [comment]
Yes that function returned sum of squares, so that solution should fix it. If you could submit a PR that would be great!

**Comment by adelavega** [comment]
Closed w/ #77
