### ISSUE TITLE
neurosynth-data & decoding error

### ISSUE THREAD

**Issue by weiliu1991** [neurosynth/neurosynth#79]
Dear all,

I am using the decoding function of the neurosynth and noticed the problem that the recently released neurosynth-data (**data_0.7.July_2018.tar.gz**) cannot be used for the decoding.

See below:
"ValueError: shapes (20,14371) and (10903,24) not aligned: 14371 (dim 1) != 10903 (dim 0)"
The error happened here: x = average_within_regions(decoder.dataset, imgs_to_decode).astype(float). 

This line will generated the **varaible x with the 14371 columns (instead of 10903)**.

This problem can be solved using the **previously released neurosynth-data** (e.g. data_0.5.February_2015.tar.gz)

Best,
Wei

**Comment by tyarkoni** [comment]
Hi Wei,

Could you please provide the code that generates the error (beginning with
the Dataset construction)? Thanks,

Tal

**Comment by weiliu1991** [comment]
Hi Tal,

Sure, I am trying to use the code from Daniel 2016 PNAS paper about principal
gradient.

(https://github.com/NeuroanatomyAndConnectivity/gradient_analysis/blob/master/05_metaanalysis_neurosynth.ipynb)

You can find all the gradient data (images to be decoded) together with the code. And I realized that the shape of the file (v3-topics-50.txt) is (10903,24).

**Comment by tyarkoni** [comment]
Ah, yeah, that makes sense. This isn't a bug with Neurosynth, that notebook should probably be updated to make sure that the version of the dataset being used for decoding is explicitly noted. In this case the v3 topics need the corresponding data file, but any file derived from the current set of studies would work fine with the current dataset. Closing this here.

**Comment by weiliu1991** [comment]
Got it. Thanks!
I will regenerate the V3 file according to the current dataset.
