### ISSUE TITLE
pA > 1?

### ISSUE THREAD

**Issue by MetaD** [neurosynth/neurosynth#85]
Hello, I have a question about how `pA` and `pFgA` images are calculated in the MetaAnalysis class. 

Say I try to do a meta-analytic contrast on two terms "beliefs" and "percept":
```
import neurosynth as ns
dataset = ns.Dataset.load('database.pkl')
ids = dataset.get_studies(features='beliefs')
ids2 = dataset.get_studies(features='percept')
meta = ns.MetaAnalysis(dataset=dataset, ids=ids, ids2=ids2)
```
Now I thought the `pA` map is supposed to be a _probability_ of baseline activation, but I noticed it's often greater than 1, which didn't make much sense to me:
```
>>> len(meta.images['pA'])
228453
>>> np.sum(meta.images['pA'] > 1)
130505
```

In [this line](https://github.com/neurosynth/neurosynth/blob/master/neurosynth/analysis/meta.py#L128), the `pA` image is calculated by dividing the number of activations of each voxel in _the entire database_, by the size of _given study universe_ (in this case the total number of studies is only 120), which seems to be the reason why it's greater than 1. Afterwards, [the `pFgA` image](https://github.com/neurosynth/neurosynth/blob/master/neurosynth/analysis/meta.py#L134) also seems to be based on this `pA` image, but both `pAgF` and  `pF` seem to be restricted to the given study universe, rather than the entire dataset.

I guess this is only an issue with these two images when contrasting two terms. Is it some specific consideration that pA and pAgF are rescaled?

Thanks!

**Comment by tyarkoni** [comment]
At first glance, this looks like a bug—thanks for catching it! Let me know if you want to submit a PR, otherwise I'll fix it when I have a chance.

**Comment by MetaD** [comment]
OK cool I can perhaps submit a PR later.

Just have another question about the `pAgF_given_pF=0.50` (or `pAgF_prior`) image on [this line](https://github.com/neurosynth/neurosynth/blob/master/neurosynth/analysis/meta.py#L138). Seems like it equals to 
` p'(F)  * p(A|F) + (1 - p'(F) ) * p(A|~F)`
`=  p'(A, F) + p'(A, ~F)`
`=  p'(A)`
... where `p'` denotes a probability based on the given prior.

So it sounds like this map is not actually conditioned on `p(F)` as the name `pAgF_given_pF` indicates, but just a probability of activation based on the given prior? Is this understanding correct? (If so, would `pA_given_pF` be a better name?) Thanks!

**Comment by tyarkoni** [comment]
Yes, I think that's right—it should be named `pA_given_pF`. Thanks! (Feel free to include in a PR if you submit one.)
