### ISSUE TITLE
neurosynth.org is down

### ISSUE THREAD

**Issue by kchawla-pi** [neurosynth/neurosynth#89]
The neurosynth.org server is down. When canwe expect it to be accessible again?
Thanks!

**Comment by tyarkoni** [comment]
It's up. In future, please open an issue on [neurosynth-web](https://github.com/neurosynth/neurosynth-web/issues) for issues related to the web service. Thanks!

**Comment by kchawla-pi** [comment]
WHoops thanks will rememebr to use neurosynth-web next time
