### ISSUE TITLE
use NIDM results for decoder

### ISSUE THREAD

**Issue by Remi-Gau** [neurosynth/neurosynth#92]
Sorry if I missed that but I don't think that the decoder accepts results that have been uploaded as NIDM results on neurovault. Our of curiosity: is that something that would be hard to implement?

**Comment by tyarkoni** [comment]
Not sure... can you point to an example collection? Thanks!

**Comment by Remi-Gau** [comment]
here are a couple:
https://identifiers.org/neurovault.collection:1425
https://identifiers.org/neurovault.collection:4172

i think that Camille had written a python package to read them: https://github.com/incf-nidash/nidmresults

**Comment by tyarkoni** [comment]
It looks like it's working okay... For reasons that are unclear to me, NeuroVault lists the NIDM result files as images. But if you ignore that and only look at the files that are actually images, they decode fine.

**Comment by tyarkoni** [comment]
Closing, but feel free to re-open if the above is incorrect.
